version: "3.9"

services:
  runbook_agent:
    build: .
    ports:
      - "8111:8111"
    volumes:
      - .:/runbook_agent
    environment:
      - ENVIRONMENT=DEV
    command: uvicorn runbook_agent.main:app --host 0.0.0.0 --port 8111